[default]
ollama_host = "http://localhost:11434"
llm_model = "qwen2.5-coder:7b"
embed_model = "nomic-embed-text"
data_dir = "~/.code-rag/data"
supported_extensions = [".py", ".js", ".ts", ".less", ".css", ".json", ".md", ".toml", ".yaml"]
exclude_paths = ["**/data/**"]

[default.ext_map]
py = "python"
js = "javascript"
ts = "typescript"
json = "json"
md = "markdown"
toml = "toml"
yaml = "yaml"
less = "less"
css = "css"
